### ISSUE TITLE
Acceso rápido a la sábana informativa desde la pantalla de inicio.

### ISSUE THREAD

**Issue by ClaudiaRmRm** [OlivIAfAIrLac/Olivia#10]
**Historia de usuario:**
Como usuario o administrador de Olivia, quiero poder acceder fácilmente a la sábana informativa desde la pantalla de inicio para obtener información actualizada de manera más rápida y sencilla.

**Criterios de aceptación:**

1. Debe haber un acceso directo o un botón claramente visible en la pantalla de inicio que indique "Sábana Informativa" o un icono representativo.
2. Al hacer clic en el acceso directo o el botón, el usuario debe ser redirigido de inmediato a la página o sección que contiene la sábana informativa.
3. El acceso directo o botón debe ser intuitivo y fácil de encontrar para que los usuarios puedan acceder a la sábana informativa sin dificultad.

**Comment by nachomartinez30** [comment]
Buen dia!
Adjunto preview del boton para aprovacion 


![Image](https://github.com/OlivIAfAIrLac/Olivia/assets/17676457/3d3273d9-eabe-4241-abe9-cf24f517344e)

**Comment by ClaudiaRmRm** [comment]
Confirmo
