### ISSUE TITLE
Gestión de expedientes por parte del administrador.

### ISSUE THREAD

**Issue by ClaudiaRmRm** [OlivIAfAIrLac/Olivia#12]
Como administrador de la plataforma Olivia, necesito la capacidad de editar y eliminar expedientes creados en la aplicación para mantener la precisión y la integridad de los datos.

**Criterios de aceptación:**

1. En la vista de administrador de la pantalla principal, donde se despliegan todos los expedientes de las personas atendidas, tendrá que haber una opción de borrar o editar dichos expedientes.
2. Para la edición de expedientes, el administrador debe tener acceso a todos los campos y detalles del expediente para realizar modificaciones, incluyendo texto, fechas, y archivos adjuntos.

**Comment by nachomartinez30** [comment]
Buen dia!
adjunto un preview de la vista de usuario ADMIN para el manejo de expedientes:

![image](https://github.com/OlivIAfAIrLac/Olivia/assets/17676457/5954f4f7-16fe-4148-b1cf-3289403de3ae)

espero la aprobacion previa a la migracion de cambios

**Comment by ClaudiaRmRm** [comment]
Se ve bien, confirmo el cambio.
