### ISSUE TITLE
Problema al crear y acceder a cuentas de usuario sin correo electrónico

### ISSUE THREAD

**Issue by ClaudiaRmRm** [OlivIAfAIrLac/Olivia#16]
Actualmente, nuestro sistema permite la creación de cuentas de usuario sin un correo electrónico asociado. Sin embargo, una vez que los usuarios intentan acceder a sus cuentas, se les solicita un correo electrónico que no tienen, lo que les impide acceder a su cuenta.

**Pasos para reproducir el problema:**

Ir al formulario de registro de usuario.
Ingresar un nombre de usuario y una contraseña.
Opcional: No ingresar una dirección de correo electrónico.
Completar el registro.

**Comportamiento esperado:**
El sistema debería permitir a los usuarios crear cuentas sin correo electrónico, ya que es una opción válida según nuestro diseño.

**Comportamiento actual:**
El sistema permite la creación de cuentas sin correo electrónico, pero impide el acceso posterior a estas cuentas al solicitar un correo electrónico.

![image](https://github.com/OlivIAfAIrLac/Olivia/assets/97906921/f6200a57-cb5f-4f7e-a8af-8066fe8f70e6)

**Comment by nachomartinez30** [comment]
Buenas tardes, este es el actual mensaje cierto?
![image](https://github.com/OlivIAfAIrLac/Olivia/assets/17676457/4ce6951a-5bb2-4a66-96ce-cb17b796806d)

**Comment by nachomartinez30** [comment]
Listo, deberia permitirles acceder con usuarios

**Comment by ClaudiaRmRm** [comment]
Resuelto
